var pages = {
                    "login":function(){
    $('body').addClass("login-page");
    //Navbar
    app_html="";
    app_html+='<nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">';
        app_html+='<div class="container">';
         app_html+=' <div class="navbar-wrapper">';
            app_html+='<a class="navbar-brand" href="#">Candidate Profiling System</a>';
          app_html+='</div>';
        app_html+='</div>';
    app_html+=' </nav>';
    //End Navbar

    app_html +='  <div class="wrapper wrapper-full-page ">';
    app_html +='    <div class="full-page section-image" filter-color="blue">';
    app_html +='      <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->';
    app_html +='      <div class="content">';
    app_html +='        <div class="container">';
    app_html +='          <div class="col-lg-4 col-md-6 ml-auto mr-auto">';
    app_html +='            <form class="form" id="login-form" method="" action="">';
    app_html +='              <div class="card card-login">';
    app_html +='                <div class="card-header ">';
    app_html +='                  <div class="card-header ">';
    app_html +='                    <h3 class="header text-center">Login</h3>';
    app_html +='                  </div>';
    app_html +='                </div>';
    app_html +='                <div class="card-body ">';
    app_html +='                  <div class="input-group">';
    app_html +='                    <div class="input-group-prepend">';
    app_html +='                      <span class="input-group-text">';
    app_html +='                        <i class="nc-icon nc-single-02"></i>';
    app_html +='                      </span>';
    app_html +='                    </div>';
    app_html +='                    <input type="text" class="form-control" name="username" placeholder="Username" autocomplete="off" required>';
    app_html +='                  </div>';
    app_html +='                  <div class="input-group">';
    app_html +='                    <div class="input-group-prepend">';
    app_html +='                      <span class="input-group-text">';
    app_html +='                        <i class="nc-icon nc-key-25"></i>';
    app_html +='                      </span>';
    app_html +='                    </div>';
    app_html +='                    <input type="password" name="password" placeholder="Password" class="form-control" required>';
    app_html +='                  </div>';
    app_html +='                  <div class="form-text text-danger text-center font-weight-bold" id="login-notice"></div>';
    app_html +='                  <br/>';
    app_html +='                  <div class="form-group">';
    app_html +='                    <div class="form-check">';
    app_html +='                      <label class="form-check-label">';
    app_html +='                        <input class="form-check-input" type="checkbox" value="" checked="">';
    app_html +='                        <span class="form-check-sign"></span>';
    app_html +='                        Stay logged in';
    app_html +='                      </label>';
    app_html +='                    </div>';
    app_html +='                  </div>';
    app_html +='                </div>';
    app_html +='                <div class="card-footer">';
    app_html +='                  <button type="submit" class="btn btn-outline-primary btn-round btn-block mb-3 log-me-in">Let\'s go</button>';
    app_html +='                </div>';
    app_html +='              </div>';
    app_html +='            </form>';
    app_html +='          </div>';
    app_html +='        </div>';
    app_html +='      </div>';
    app_html +='    </div>';
    app_html +='  </div>';
    $("#app").html(app_html);
    $page = $('.full-page');
    image_src = 'app/assets/bs4/img/bg/ben-white.jpg';

    if (image_src !== undefined) {
      image_container = '<div class="full-page-background" style="background-image: url(' + image_src + ') "/>';
      $page.append(image_container);
    }
                    }



                    ,"dashboard":function(){
                           $('body').removeClass("login-page");
                            // app html

                            var app_html = "",
                                sidebar = pages.sidebar();
                            app_html += sidebar;
                            // inject to 'app' in index.html
                            $("#app").html(app_html);
                            (function() {
                            isWindows = navigator.platform.indexOf('Win') > -1 ? true : false;

                            if (isWindows) {
                              // if we are on windows OS we activate the perfectScrollbar function
                              $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

                              $('html').addClass('perfect-scrollbar-on');
                            } else {
                              $('html').addClass('perfect-scrollbar-off');
                            }
                          })();
                    },
                    "sidebar":function(){
                      var sidebar = "";
sidebar += '  <div class="wrapper ">';
sidebar += '    <div class="sidebar" data-color="brown" data-active-color="danger">';
sidebar += '      <!--';
sidebar += '        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"';
sidebar += '    -->';
sidebar += '      <div class="logo">';
sidebar += '        <a href="#" class="simple-text logo-mini">';
sidebar += '          <div class="logo-image-small">';
sidebar += '            CPS';
sidebar += '          </div>';
sidebar += '        </a>';
sidebar += '        <a href="#" class="simple-text logo-normal">';
sidebar += '          <div class="logo-image-big">';
sidebar += '            <img src="app/assets/images/optimus-and-conexus-logo.png" style="margin-left:-20px">';
sidebar += '          </div>';
sidebar += '        </a>';
sidebar += '      </div>';
sidebar += '      <div class="sidebar-wrapper">';
sidebar += '        <div class="user">';
sidebar += '          <div class="photo">';
sidebar += '            <!--img src="../assets/img/faces/ayo-ogunseinde-2.jpg" /-->';
sidebar += '          </div>';
sidebar += '          <div class="info">';
sidebar += '            <a data-toggle="collapse" href="#collapseExample" class="collapsed">';
sidebar += '              <span>';
sidebar +=                 localStorage.getItem('username');
sidebar += '                <b class="caret"></b>';
sidebar += '              </span>';
sidebar += '            </a>';
sidebar += '            <div class="clearfix"></div>';
sidebar += '            <div class="collapse" id="collapseExample">';
sidebar += '              <ul class="nav">';
sidebar += '                <li>';
sidebar += '                  <a href="#">';
sidebar += '                    <span class="sidebar-mini-icon">MP</span>';
sidebar += '                    <span class="sidebar-normal">My Profile</span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="#">';
sidebar += '                    <span class="sidebar-mini-icon">EP</span>';
sidebar += '                    <span class="sidebar-normal">Edit Profile</span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="#">';
sidebar += '                    <span class="sidebar-mini-icon">S</span>';
sidebar += '                    <span class="sidebar-normal">Settings</span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="#">';
sidebar += '                    <span class="sidebar-mini-icon">LO</span>';
sidebar += '                    <span class="sidebar-normal" id="logmeout">Log out</span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '              </ul>';
sidebar += '            </div>';
sidebar += '          </div>';
sidebar += '        </div>';
sidebar += '        <ul class="nav">';
sidebar += '          <li class="active">';
sidebar += '            <a href="../examples/dashboard.html">';
sidebar += '              <i class="nc-icon nc-bank"></i>';
sidebar += '              <p>Dashboard</p>';
sidebar += '            </a>';
sidebar += '          </li>';
sidebar += '          <li>';
sidebar += '            <a data-toggle="collapse" href="#pagesExamples">';
sidebar += '              <i class="nc-icon nc-book-bookmark"></i>';
sidebar += '              <p>';
sidebar += '                Pages';
sidebar += '                <b class="caret"></b>';
sidebar += '              </p>';
sidebar += '            </a>';
sidebar += '            <div class="collapse " id="pagesExamples">';
sidebar += '              <ul class="nav">';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/pages/timeline.html">';
sidebar += '                    <span class="sidebar-mini-icon">T</span>';
sidebar += '                    <span class="sidebar-normal"> Timeline </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/pages/login.html">';
sidebar += '                    <span class="sidebar-mini-icon">L</span>';
sidebar += '                    <span class="sidebar-normal"> Login </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/pages/register.html">';
sidebar += '                    <span class="sidebar-mini-icon">R</span>';
sidebar += '                    <span class="sidebar-normal"> Register </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/pages/lock.html">';
sidebar += '                    <span class="sidebar-mini-icon">LS</span>';
sidebar += '                    <span class="sidebar-normal"> Lock Screen </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/pages/user.html">';
sidebar += '                    <span class="sidebar-mini-icon">UP</span>';
sidebar += '                    <span class="sidebar-normal"> User Profile </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '              </ul>';
sidebar += '            </div>';
sidebar += '          </li>';
sidebar += '          <li>';
sidebar += '            <a data-toggle="collapse" href="#componentsExamples">';
sidebar += '              <i class="nc-icon nc-layout-11"></i>';
sidebar += '              <p>';
sidebar += '                Components';
sidebar += '                <b class="caret"></b>';
sidebar += '              </p>';
sidebar += '            </a>';
sidebar += '            <div class="collapse " id="componentsExamples">';
sidebar += '              <ul class="nav">';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/components/buttons.html">';
sidebar += '                    <span class="sidebar-mini-icon">B</span>';
sidebar += '                    <span class="sidebar-normal"> Buttons </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/components/grid.html">';
sidebar += '                    <span class="sidebar-mini-icon">G</span>';
sidebar += '                    <span class="sidebar-normal"> Grid System </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/components/panels.html">';
sidebar += '                    <span class="sidebar-mini-icon">P</span>';
sidebar += '                    <span class="sidebar-normal"> Panels </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/components/sweet-alert.html">';
sidebar += '                    <span class="sidebar-mini-icon">SA</span>';
sidebar += '                    <span class="sidebar-normal"> Sweet Alert </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/components/notifications.html">';
sidebar += '                    <span class="sidebar-mini-icon">N</span>';
sidebar += '                    <span class="sidebar-normal"> Notifications </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/components/icons.html">';
sidebar += '                    <span class="sidebar-mini-icon">I</span>';
sidebar += '                    <span class="sidebar-normal"> Icons </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/components/typography.html">';
sidebar += '                    <span class="sidebar-mini-icon">T</span>';
sidebar += '                    <span class="sidebar-normal"> Typography </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '              </ul>';
sidebar += '            </div>';
sidebar += '          </li>';
sidebar += '          <li>';
sidebar += '            <a data-toggle="collapse" href="#formsExamples">';
sidebar += '              <i class="nc-icon nc-ruler-pencil"></i>';
sidebar += '              <p>';
sidebar += '                Forms';
sidebar += '                <b class="caret"></b>';
sidebar += '              </p>';
sidebar += '            </a>';
sidebar += '            <div class="collapse " id="formsExamples">';
sidebar += '              <ul class="nav">';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/forms/regular.html">';
sidebar += '                    <span class="sidebar-mini-icon">RF</span>';
sidebar += '                    <span class="sidebar-normal"> Regular Forms </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/forms/extended.html">';
sidebar += '                    <span class="sidebar-mini-icon">EF</span>';
sidebar += '                    <span class="sidebar-normal"> Extended Forms </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/forms/validation.html">';
sidebar += '                    <span class="sidebar-mini-icon">V</span>';
sidebar += '                    <span class="sidebar-normal"> Validation Forms </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/forms/wizard.html">';
sidebar += '                    <span class="sidebar-mini-icon">W</span>';
sidebar += '                    <span class="sidebar-normal"> Wizard </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '              </ul>';
sidebar += '            </div>';
sidebar += '          </li>';
sidebar += '          <li>';
sidebar += '            <a data-toggle="collapse" href="#tablesExamples">';
sidebar += '              <i class="nc-icon nc-single-copy-04"></i>';
sidebar += '              <p>';
sidebar += '                Tables';
sidebar += '                <b class="caret"></b>';
sidebar += '              </p>';
sidebar += '            </a>';
sidebar += '            <div class="collapse " id="tablesExamples">';
sidebar += '              <ul class="nav">';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/tables/regular.html">';
sidebar += '                    <span class="sidebar-mini-icon">RT</span>';
sidebar += '                    <span class="sidebar-normal"> Regular Tables </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/tables/extended.html">';
sidebar += '                    <span class="sidebar-mini-icon">ET</span>';
sidebar += '                    <span class="sidebar-normal"> Extended Tables </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/tables/datatables.net.html">';
sidebar += '                    <span class="sidebar-mini-icon">DT</span>';
sidebar += '                    <span class="sidebar-normal"> DataTables.net </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '              </ul>';
sidebar += '            </div>';
sidebar += '          </li>';
sidebar += '          <li>';
sidebar += '            <a data-toggle="collapse" href="#mapsExamples">';
sidebar += '              <i class="nc-icon nc-pin-3"></i>';
sidebar += '              <p>';
sidebar += '                Maps';
sidebar += '                <b class="caret"></b>';
sidebar += '              </p>';
sidebar += '            </a>';
sidebar += '            <div class="collapse " id="mapsExamples">';
sidebar += '              <ul class="nav">';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/maps/google.html">';
sidebar += '                    <span class="sidebar-mini-icon">GM</span>';
sidebar += '                    <span class="sidebar-normal"> Google Maps </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/maps/fullscreen.html">';
sidebar += '                    <span class="sidebar-mini-icon">FSM</span>';
sidebar += '                    <span class="sidebar-normal"> Full Screen Map </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '                <li>';
sidebar += '                  <a href="../examples/maps/vector.html">';
sidebar += '                    <span class="sidebar-mini-icon">VM</span>';
sidebar += '                    <span class="sidebar-normal"> Vector Map </span>';
sidebar += '                  </a>';
sidebar += '                </li>';
sidebar += '              </ul>';
sidebar += '            </div>';
sidebar += '          </li>';
sidebar += '          <li>';
sidebar += '            <a href="../examples/widgets.html">';
sidebar += '              <i class="nc-icon nc-box"></i>';
sidebar += '              <p>Widgets</p>';
sidebar += '            </a>';
sidebar += '          </li>';
sidebar += '          <li>';
sidebar += '            <a href="../examples/charts.html">';
sidebar += '              <i class="nc-icon nc-chart-bar-32"></i>';
sidebar += '              <p>Charts</p>';
sidebar += '            </a>';
sidebar += '          </li>';
sidebar += '          <li>';
sidebar += '            <a href="../examples/calendar.html">';
sidebar += '              <i class="nc-icon nc-calendar-60"></i>';
sidebar += '              <p>Calendar</p>';
sidebar += '            </a>';
sidebar += '          </li>';
sidebar += '        </ul>';
sidebar += '      </div>';
sidebar += '    </div>';
sidebar += '    <div class="main-panel">';
sidebar += '      <!-- Navbar -->';
sidebar += '      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">';
sidebar += '        <div class="container-fluid">';
sidebar += '          <div class="navbar-wrapper">';
sidebar += '            <div class="navbar-minimize">';
sidebar += '              <button id="minimizeSidebar" class="btn btn-icon btn-round">';
sidebar += '                <i class="nc-icon nc-minimal-right text-center visible-on-sidebar-mini"></i>';
sidebar += '                <i class="nc-icon nc-minimal-left text-center visible-on-sidebar-regular"></i>';
sidebar += '              </button>';
sidebar += '            </div>';
sidebar += '            <div class="navbar-toggle">';
sidebar += '              <button type="button" class="navbar-toggler">';
sidebar += '                <span class="navbar-toggler-bar bar1"></span>';
sidebar += '                <span class="navbar-toggler-bar bar2"></span>';
sidebar += '                <span class="navbar-toggler-bar bar3"></span>';
sidebar += '              </button>';
sidebar += '            </div>';
sidebar += '            <a class="navbar-brand" href="#pablo">Dashboard</a>';
sidebar += '          </div>';
sidebar += '          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">';
sidebar += '            <span class="navbar-toggler-bar navbar-kebab"></span>';
sidebar += '            <span class="navbar-toggler-bar navbar-kebab"></span>';
sidebar += '            <span class="navbar-toggler-bar navbar-kebab"></span>';
sidebar += '          </button>';
sidebar += '          <div class="collapse navbar-collapse justify-content-end" id="navigation">';
sidebar += '            <!--form>';
sidebar += '              <div class="input-group no-border">';
sidebar += '                <input type="text" value="" class="form-control" placeholder="Search...">';
sidebar += '                <div class="input-group-append">';
sidebar += '                  <div class="input-group-text">';
sidebar += '                    <i class="nc-icon nc-zoom-split"></i>';
sidebar += '                  </div>';
sidebar += '                </div>';
sidebar += '              </div>';
sidebar += '            </form-->';
sidebar += '            <ul class="navbar-nav">';
sidebar += '              <!--li class="nav-item">';
sidebar += '                <a class="nav-link btn-magnify" href="#pablo">';
sidebar += '                  <i class="nc-icon nc-layout-11"></i>';
sidebar += '                  <p>';
sidebar += '                    <span class="d-lg-none d-md-block">Stats</span>';
sidebar += '                  </p>';
sidebar += '                </a>';
sidebar += '              </li-->';
sidebar += '              <li class="nav-item btn-rotate dropdown">';
sidebar += '                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">';
sidebar += '                  <i class="nc-icon nc-bell-55"></i>';
sidebar += '                  <p>';
sidebar += '                    <span class="d-lg-none d-md-block">Some Actions</span>';
sidebar += '                  </p>';
sidebar += '                </a>';
sidebar += '                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">';
sidebar += '                  <a class="dropdown-item" href="#">Action</a>';
sidebar += '                  <a class="dropdown-item" href="#">Another action</a>';
sidebar += '                  <a class="dropdown-item" href="#">Something else here</a>';
sidebar += '                </div>';
sidebar += '              </li>';
sidebar += '              <!--li class="nav-item">';
sidebar += '                <a class="nav-link btn-rotate" href="#pablo">';
sidebar += '                  <i class="nc-icon nc-settings-gear-65"></i>';
sidebar += '                  <p>';
sidebar += '                    <span class="d-lg-none d-md-block">Account</span>';
sidebar += '                  </p>';
sidebar += '                </a>';
sidebar += '              </li-->';
sidebar += '            </ul>';
sidebar += '          </div>';
sidebar += '        </div>';
sidebar += '      </nav>';
sidebar += '      <!-- End Navbar -->';
sidebar += '      <!-- <div class="panel-header">';
return sidebar;
                    }
                }